[tool.poetry]
name = "bitcask-python"
version = "0.1.0"
description = ""
authors = ["Aryav Bharali <bharali@wisc.edu>"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
